// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH2qw_NVxDazbpLxajWpZ-vuqXRkA62MQ',
    appId: '1:896951121335:web:c7053588bdda9778eca432',
    messagingSenderId: '896951121335',
    projectId: 'nutriscan-fb46c',
    authDomain: 'nutriscan-fb46c.firebaseapp.com',
    storageBucket: 'nutriscan-fb46c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkLKoEWndoE0-4vSQqourUoQcBRoYrDk0',
    appId: '1:896951121335:android:8afd1d15ef9afe7ceca432',
    messagingSenderId: '896951121335',
    projectId: 'nutriscan-fb46c',
    storageBucket: 'nutriscan-fb46c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKFlBwhLyi2sRkFN9Przs2P80GqZp1gIc',
    appId: '1:896951121335:ios:1f6adc601df941f0eca432',
    messagingSenderId: '896951121335',
    projectId: 'nutriscan-fb46c',
    storageBucket: 'nutriscan-fb46c.appspot.com',
    iosBundleId: 'com.example.nutriscan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKFlBwhLyi2sRkFN9Przs2P80GqZp1gIc',
    appId: '1:896951121335:ios:1f6adc601df941f0eca432',
    messagingSenderId: '896951121335',
    projectId: 'nutriscan-fb46c',
    storageBucket: 'nutriscan-fb46c.appspot.com',
    iosBundleId: 'com.example.nutriscan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH2qw_NVxDazbpLxajWpZ-vuqXRkA62MQ',
    appId: '1:896951121335:web:c4324afca5274c8feca432',
    messagingSenderId: '896951121335',
    projectId: 'nutriscan-fb46c',
    authDomain: 'nutriscan-fb46c.firebaseapp.com',
    storageBucket: 'nutriscan-fb46c.appspot.com',
  );

}